# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vcsp039oj2-1nndnqRVBkcf9ACbSSIG1
"""



# Define a list with both positive and negative numbers
numbers = [-10, 5, -3, 8, -1, 0, 7, -6, 12]

# Print positive numbers
print("Positive numbers in the list are:")
for num in numbers:
    if num > 0:
        print(num)